export const DEMO_EVENTS = [
  {
    id: '1',
    title: 'Afrobeats Music Festival',
    description: 'Enjoy the best of African music with international artists',
    fullDescription: 'Experience the rhythm and soul of the continent at the Afrobeats Music Festival. Featuring top artists from West and East Africa, this festival celebrates our common culture through music, dance, and art. Join thousands of fans for a night of unforgettable performances.',
    date: '2026-06-15',
    time: '18:00',
    location: 'Lilongwe, Malawi',
    venue: 'Safari Park Hotel',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    category: 'music',
    ticketsTotal: 500,
    ticketsAvailable: 250,
    price: 3500,
    organizer: 'org_1',
    organizerEmail: 'music@events.com',
    status: 'active',
    busTransport: true,
    seatingChart: false,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: '2',
    title: 'Tech Innovation Summit 2026',
    description: 'Learn from industry leaders about the future of technology',
    fullDescription: 'The Tech Innovation Summit brings together the brightest minds in technology from across the globe. Focus areas include AI for development, fintech in Africa, and sustainable energy solutions. Network with founders, investors, and engineers.',
    date: '2026-06-20',
    time: '09:00',
    location: 'Blantyre, Malawi',
    venue: 'Convention Center',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    category: 'conference',
    ticketsTotal: 600,
    ticketsAvailable: 500,
    price: 2500,
    organizer: 'org_2',
    organizerEmail: 'tech@events.com',
    status: 'active',
    busTransport: true,
    seatingChart: true,
    createdAt: new Date('2026-01-05').toISOString(),
  },
  {
    id: '3',
    title: 'Football Championship Final',
    description: 'Watch the most exciting football match of the season',
    fullDescription: 'The pinnacle of football excellence on the continent. Two giants of African football clash in this high-stakes final. Experience the atmosphere, the passion, and the glory as we crown a new champion.',
    date: '2026-07-02',
    time: '15:00',
    location: 'Zomba, Malawi',
    venue: 'National Stadium',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&h=600&fit=crop',
    category: 'sports',
    ticketsTotal: 50000,
    ticketsAvailable: 1000,
    price: 5000,
    organizer: 'org_3',
    organizerEmail: 'sports@league.com',
    status: 'active',
    busTransport: false,
    seatingChart: true,
    createdAt: new Date('2026-01-10').toISOString(),
  },
  {
    id: '4',
    title: 'Comedy Night Extravaganza',
    description: 'Laugh out loud with top comedians from across the continent',
    fullDescription: 'Prepare for an evening of side-splitting laughter as the funniest comedians on the continent take the stage. From observational humor to satire, there is something for everyone in this star-studded lineup.',
    date: '2026-07-10',
    time: '20:00',
    location: 'Addis Ababa, Ethiopia',
    venue: 'Grand Theater',
    image: 'https://images.unsplash.com/photo-1540575467063-178f50002c4b?w=800&h=600&fit=crop',
    category: 'festival',
    ticketsTotal: 500,
    ticketsAvailable: 300,
    price: 2000,
    organizer: 'org_4',
    organizerEmail: 'comedy@nights.com',
    status: 'active',
    busTransport: false,
    seatingChart: false,
    createdAt: new Date('2026-01-15').toISOString(),
  },
  {
    id: '5',
    title: 'Web Development Workshop',
    description: 'Master modern web development with hands-on training',
    fullDescription: 'A deep dive into modern frontend and backend technologies. Learn Next.js, Firebase, and Tailwind CSS from industry professionals. This hands-on workshop is designed to take your skills to the next level.',
    date: '2026-07-15',
    time: '10:00',
    location: 'Dar es Salaam, Tanzania',
    venue: 'Tech Hub',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
    category: 'workshop',
    ticketsTotal: 50,
    ticketsAvailable: 50,
    price: 3000,
    organizer: 'org_2',
    organizerEmail: 'tech@events.com',
    status: 'active',
    busTransport: false,
    seatingChart: false,
    createdAt: new Date('2026-01-20').toISOString(),
  },
  {
    id: '6',
    title: 'Annual Food Festival',
    description: 'Taste delicious cuisine from across Africa',
    fullDescription: 'A gastronomic journey across the continent. Sample traditional dishes and modern interpretations of African cuisine. With live cooking demonstrations and wine tasting, it is a feast for all the senses.',
    date: '2026-07-25',
    time: '12:00',
    location: 'Kigali, Rwanda',
    venue: 'Central Park',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561404?w=800&h=600&fit=crop',
    category: 'festival',
    ticketsTotal: 2000,
    ticketsAvailable: 750,
    price: 1500,
    organizer: 'org_1',
    organizerEmail: 'music@events.com',
    status: 'active',
    busTransport: true,
    seatingChart: false,
    createdAt: new Date('2026-01-25').toISOString(),
  },
];

export const DEMO_BOOKINGS = [
  {
    id: 'BK-001-2026',
    userId: 'demo_user_1',
    eventId: '1',
    eventTitle: 'Afrobeats Music Festival',
    eventDate: '2026-06-15',
    eventTime: '18:00',
    eventLocation: 'Lilongwe, Malawi',
    eventVenue: 'Safari Park Hotel',
    eventImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
    quantity: 2,
    price: 3500,
    totalAmount: 7000,
    status: 'confirmed',
    bookingDate: '2026-05-01',
    ticketNumbers: ['TK-00001', 'TK-00002'],
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    phone: '+265880000000',
    paymentMethod: 'MPesa',
    busTransport: true,
    tier: 'VIP',
    createdAt: new Date('2026-05-01').toISOString(),
  },
  {
    id: 'BK-002-2026',
    userId: 'demo_user_1',
    eventId: '2',
    eventTitle: 'Tech Innovation Summit 2026',
    eventDate: '2026-06-20',
    eventTime: '09:00',
    eventLocation: 'Blantyre, Malawi',
    eventVenue: 'Convention Center',
    eventImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
    quantity: 1,
    price: 2500,
    totalAmount: 2500,
    status: 'confirmed',
    bookingDate: '2026-05-10',
    ticketNumbers: ['TK-10001'],
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    phone: '+265880000000',
    paymentMethod: 'Credit Card',
    busTransport: false,
    createdAt: new Date('2026-05-10').toISOString(),
  },
  {
    id: 'BK-003-2026',
    userId: 'demo_user_1',
    eventId: '3',
    eventTitle: 'Football Championship Final',
    eventDate: '2026-07-02',
    eventTime: '15:00',
    eventLocation: 'Zomba, Malawi',
    eventVenue: 'National Stadium',
    eventImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&h=300&fit=crop',
    quantity: 3,
    price: 5000,
    totalAmount: 15000,
    status: 'pending',
    bookingDate: '2026-05-20',
    ticketNumbers: ['TK-20001', 'TK-20002', 'TK-20003'],
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    phone: '+265880000000',
    paymentMethod: 'Airtel Money',
    busTransport: false,
    createdAt: new Date('2026-05-20').toISOString(),
  },
];

export const DEMO_ANALYTICS = {
  revenue: [
    { month: 'Jan', revenue: 45000 },
    { month: 'Feb', revenue: 52000 },
    { month: 'Mar', revenue: 48000 },
    { month: 'Apr', revenue: 61000 },
    { month: 'May', revenue: 55000 },
    { month: 'Jun', revenue: 67000 },
  ],
  sales: [
    { date: 'Mon', sales: 120 },
    { date: 'Tue', sales: 145 },
    { date: 'Wed', sales: 110 },
    { date: 'Thu', sales: 180 },
    { date: 'Fri', sales: 200 },
    { date: 'Sat', sales: 220 },
    { date: 'Sun', sales: 190 },
  ],
};

export const DEMO_USERS = [
  {
    uid: 'demo_user_1',
    email: 'user@zosavuta.com',
    displayName: 'Demo User',
    role: 'customer',
  },
  {
    uid: 'org_1',
    email: 'organizer@zosavuta.com',
    displayName: 'Premium Events Org',
    role: 'organizer',
  },
];
